### ISSUE TITLE
PyFiglet not found (Large ASCII word art disabled).

### ISSUE THREAD

**Issue by Devendrabhat** [thetianshuhuang/print#1]
Error: PyFiglet not found (Large ASCII word art disabled)
This Error came when I tried to do "from print import *".

Solution:- 
pip install pyfiglet

So, I feel you need to mention pyfiglet in requirements.

**Comment by thetianshuhuang** [comment]
I added pyfiglet to the requirements; this should show up in version 1.1.3.

Thanks for your feedback!
